version: '3.7'

volumes:
    chanllenge_php-db:
        external: true

networks:
    chanllenge_php-networks:
        external: true

services:
    chanllenge_php-app:
        image: ambientum/php:8.0-nginx
        container_name: chanllenge_php-app
        volumes:
            - .:/var/www/app
        ports:
            - ${SERVER_PORT_APP}:8080
        links:
            - chanllenge_php-db
        networks:
            - chanllenge_php-networks

    chanllenge_php-db:
        image: mysql:5.7
        container_name: chanllenge_php-db
        volumes:
            - chanllenge_php-db:/var/lib/mysql
        ports:
            - 33061:3306
        environment:
            - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
            - "MYSQL_DATABASE=database"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=secret"
        networks:
            - chanllenge_php-networks